language: python
python:
- '3.5'
env:
- TOXENV=py35
- TOXENV=pep8
before_install:
- pip install tox
script:
- tox
notifications:
  slack:
    secure: O669//gnFi4qSnDzff9Di+aXIyrlqKp4m7/+A04OqOGw8X6LcC7cUu6FNp3ccyI0CJ8qD5BeQm9vASMNMemOvX4n6b5nuDk66wvB6FstYzZACLs0Nhkcp1FvKQjOAAON7lcfaUiNJWJL6wQOz8qlarhb1nULJi+eeaZpWTcZZg+i11YCgS49gWNIaeWDHDGWl5aHXLZhoJMktWCONaxRUZgmqv0ikL8pW8wTKsk1VqE9ObqHbYRZjUVSmPqbcApZ4ACbCIR2uF1PP4VuF7IsOPAKQ1DQXGRn5PGPhmmRzTNyCpw37zkn61lMSQa01vyM0rul2TgggKPZxtAwEy87SXd0/sm6a6BZ5z4PPQu70Pj7AwtTLJzXdRgKmcfpr4d1ajxiL1GcjmSE1rtxBs/mEtwRZEyoFCFDzg1Uo1k0GCcitoCkEzCk+o9LCzdhNSR+aaK9a/Pxip1bcsofXzliU024PvJeVh+Xeq9QwEsa2tvO7MKIDnn/msuVDZzN+lf8zg8spIIqL6gw282GU5xLfBSMI3esCD3zgaLS17IKjDUbLgEmtBmaW71ZR2zYzdFx7k84BAIvLqLFLCdHFBiLBnsmFrbEe6rOldolAxLFF7HIXz2T9eq7G83odahwlankw7SIdcyTbVXsrzGHySUDwFJdcWrFeHbsPqQZ4x140yI=
